const chapter2 = [
    { id: "2-1", title: "箇条書きリストを作ろう", content: "順番のない箇条書きを作るには、<b>ulタグ</b>と<b>liタグ</b>を使います。<br><br>右のコードの続きに、好きな食べ物をもう一つ追加してみましょう。", initialCode: "<ul>\n    <li>りんご</li>\n    <li>みかん</li>\n    \n</ul>" },
    { id: "2-2", title: "番号付きリストを作ろう", content: "順番があるリストを作るには、ulタグの代わりに <b>olタグ</b>を使います。<br><br>右のコードを完成させて、手順のリストを作ってみましょう。", initialCode: "<ol>\n    <li>パソコンの電源を入れる</li>\n    <li>エディタを開く</li>\n    \n</ol>" },
    { id: "2-3", title: "リストを入れ子にしよう", content: "リストの中に、さらにリストを入れること（入れ子）もできます。<br><br>右のコードを見て、リストがどのように表示されるか確認してみましょう。", initialCode: "<ul>\n    <li>フロントエンド\n        <ul>\n            <li>HTML</li>\n            <li>CSS</li>\n        </ul>\n    </li>\n</ul>" },
    { id: "2-4", title: "テーブル（表）の基本", content: "表を作るには <b>tableタグ</b> を使います。<br>行を <b>trタグ</b> で作り、その中にデータ（セル）を <b>tdタグ</b> で作ります。<br><br>右のコードを見て、2行の表ができていることを確認しましょう。", initialCode: "<table border=\"1\">\n    <tr>\n        <td>1行目、左</td>\n        <td>1行目、右</td>\n    </tr>\n    <tr>\n        <td>2行目、左</td>\n        <td>2行目、右</td>\n    </tr>\n</table>" },
    { id: "2-5", title: "テーブルの見出しを作ろう", content: "表の見出しとなるセルには、tdタグの代わりに <b>thタグ</b> を使います。<br><br>右のコードの1行目を、tdからthに変更してみましょう。", initialCode: "<table border=\"1\">\n    <tr>\n        <td>名前</td>\n        <td>年齢</td>\n    </tr>\n    <tr>\n        <td>田中</td>\n        <td>25</td>\n    </tr>\n</table>" },
    { id: "2-6", title: "セルを横につなげよう（結合）", content: "隣り合うセルを横につなげたいときは、 <b>colspan属性</b> を使います。<br><br>右のコードで、見出しが2列分つながっているのを確認しましょう。", initialCode: "<table border=\"1\">\n    <tr>\n        <th colspan=\"2\">社員データ</th>\n    </tr>\n    <tr>\n        <td>佐藤</td>\n        <td>エンジニア</td>\n    </tr>\n</table>" },
    { id: "2-7", title: "セルを縦につなげよう", content: "上下のセルを縦につなげたいときは、 <b>rowspan属性</b> を使います。<br><br>右のコードで、A班という文字が縦につながっているのを確認しましょう。", initialCode: "<table border=\"1\">\n    <tr>\n        <th rowspan=\"2\">A班</th>\n        <td>鈴木</td>\n    </tr>\n    <tr>\n        <td>高橋</td>\n    </tr>\n</table>" },
    { id: "2-8", title: "テーブルの構造を分けよう", content: "表を「頭（thead）」「体（tbody）」「足（tfoot）」に分けることができます。<br><br>コードを見て、theadとtbodyがどう使われているか確認しましょう。", initialCode: "<table border=\"1\">\n    <thead>\n        <tr><th>商品名</th><th>価格</th></tr>\n    </thead>\n    <tbody>\n        <tr><td>りんご</td><td>100円</td></tr>\n        <tr><td>みかん</td><td>50円</td></tr>\n    </tbody>\n</table>" },
    { id: "2-9", title: "リストとテーブルの組み合わせ", content: "テーブルのセル（td）の中に、リスト（ulなど）を入れることも可能です。<br><br>右の表の「スキル」の列に、ulとliを使って箇条書きを入れてみましょう。", initialCode: "<table border=\"1\">\n    <tr>\n        <th>名前</th>\n        <th>スキル</th>\n    </tr>\n    <tr>\n        <td>山田</td>\n        <td>\n            \n        </td>\n    </tr>\n</table>" },
    { id: "2-10", title: "第2章のまとめテスト！", content: "ここまで学んだリストとテーブルを使って、「一週間の学習予定表」を作ってみましょう！<br><br>【課題】<br>1. tableを使って表を作る<br>2. 1行目はthで「曜日」「学習内容」<br>3. 2行目はtdで「月曜日」と「HTML（ulタグ）」", initialCode: "\n\n\n" }
];