const chapter7 = [
    { id: "7-1", title: "CSSってなに？", content: "CSS（シーエスエス）は、HTMLで作った骨組みに「色」「大きさ」「配置」などの<b>デザイン（見た目）を指定する言葉</b>です。<br><br>右側のエリアに、文字の色を赤色にするCSSを用意しました。まずはそのまま実行結果を確認してみましょう！", initialCode: "<style>\n    h1 {\n        color: red;\n    }\n</style>\n\n<h1>この文字が赤くなります！</h1>" },
    { id: "7-2", title: "スタイルシートの基本ルール", content: "CSSは基本的に <b>誰に { 何を: どうする; }</b> というルールで書きます。<br>・誰に ＝ セレクタ（h1やpなど）\n・何を ＝ プロパティ（colorなど）\n・どうする ＝ 値（redなど）<br>※最後にセミコロン（;）を忘れないようにしましょう！<br><br>右のコードの「red」を「blue」に書き換えてみてください。", initialCode: "<style>\n    p {\n        color: red;\n    }\n</style>\n\n<p>文字の色が変わるよ！</p>" },
    { id: "7-3", title: "文字の大きさを変えよう", content: "文字の大きさを変えるには <b>font-size</b> を使います。サイズは「px（ピクセル）」という単位を使って指定するのが基本です。<br><br>右のpタグの文字を、大きく（例：30px）してみましょう！", initialCode: "<style>\n    p {\n        font-size: 20px;\n    }\n</style>\n\n<p>文字の大きさを自由に変えてみよう。</p>" },
    { id: "7-4", title: "文字の太さを変えよう", content: "文字を太くしたり細くしたりするには <b>font-weight</b> を使います。太くしたいときは <b>bold</b> を指定します。<br><br>右のpタグの文字を太字にしてみましょう。", initialCode: "<style>\n    p {\n        font-weight: normal;\n    }\n</style>\n\n<p>この文字を太くしてみましょう！</p>" },
    { id: "7-5", title: "文字の位置を変えよう", content: "文字を真ん中寄せにしたり、右寄せにしたりするには <b>text-align</b> を使います。<br>・真ん中 ＝ center\n・右寄せ ＝ right<br><br>右の見出しを中央に寄せてみましょう！", initialCode: "<style>\n    h1 {\n        text-align: left;\n    }\n</style>\n\n<h1>中央に移動させよう</h1>" },
    { id: "7-6", title: "背景に色をつけよう", content: "文字だけでなく、要素の背景に色をつけるには <b>background-color</b> を使います。<br><br>右のpタグの背景を、好きな色（yellowやpinkなど）に変えてみましょう。", initialCode: "<style>\n    p {\n        background-color: lightblue;\n    }\n</style>\n\n<p>背景に色がついて座布団のようになります！</p>" },
    { id: "7-7", title: "文字の下線を引こう", content: "文字に下線を引いたり、逆にリンク（aタグ）の最初からある下線を消したりするには <b>text-decoration</b> を使います。<br>・下線をつける ＝ underline\n・線を消す ＝ none<br><br>右のaタグの下線を消してみましょう。", initialCode: "<style>\n    a {\n        text-decoration: underline;\n    }\n</style>\n\n<a href=\"#\">下線を消してみよう</a>" },
    { id: "7-8", title: "行の間隔（隙間）をあけよう", content: "文章が詰まっていて読みづらいときは、行の高さを <b>line-height</b> で広げます。数字（1.5や2など）で指定するのが一般的です。<br><br>右のline-heightの数字を「2.5」など大きくして、読みやすさを比べてみましょう。", initialCode: "<style>\n    p {\n        line-height: 1.2;\n    }\n</style>\n\n<p>ここに行の間隔が狭い文章があります。改行されたときの間隔が狭いと読みづらいですよね。CSSを使えば一瞬で読みやすくなります！</p>" },
    { id: "7-9", title: "フォント（字体）を変えよう", content: "文字の形をゴシック体や明朝体に変えるには <b>font-family</b> を使います。<br>・丸ゴシック風 ＝ sans-serif\n・明朝体風 ＝ serif<br><br>右の文字を明朝体風に変えてみましょう。", initialCode: "<style>\n    h2 {\n        font-family: sans-serif;\n    }\n</style>\n\n<h2>高級感のある明朝体に変えてみよう</h2>" },
    { id: "7-10", title: "第7章のまとめテスト！", content: "文字のデザインを組み合わせて、おしゃれなタイトルを作ってみましょう！<br><br>【課題】\n1. 文字の色（color）を好きな色にする\n2. 文字の大きさを「36px」にする\n3. 文字の位置を「中央寄せ」にする", initialCode: "<style>\n    h1 {\n        /* ここにCSSを書いてみよう */\n        \n    }\n</style>\n\n<h1>合格目指してがんばろう！</h1>" }
];