const chapter4 = [
    { id: "4-1", title: "divタグでグループ化しよう", content: "画面の要素をひとまとめにして、あとでCSSでデザインをつけやすくするために <b>div（ディブ）タグ</b> を使います。div自体には特別な意味や見た目の変化はありません。<br><br>右のコードで2つのdivに分かれているのを確認しましょう。", initialCode: "<div>\n    <h2>グループA</h2>\n    <p>ここはグループAの中身です。</p>\n</div>\n<div>\n    <h2>グループB</h2>\n    <p>ここはグループBの中身です。</p>\n</div>" },
    { id: "4-2", title: "spanタグで文字の一部をグループ化", content: "divタグが「行全体（ブロック）」を囲むのに対し、文章の中の「文字の一部」だけを囲むときは <b>span（スパン）タグ</b> を使います。これも見た目は変わりませんが、特定の文字だけ色を変えたい時などに使います。<br><br>右の文章の「赤色」という文字をspanタグで囲んでみましょう。", initialCode: "<p>この文章の<span>赤色</span>にしたい部分だけを囲みます。</p>" },
    { id: "4-3", title: "ページの頭：headerタグ", content: "Webページの最上部にある、ロゴやメニューが並ぶエリアには <b>header（ヘッダー）タグ</b> を使います。中身はdivと同じですが、ブラウザに「ここがヘッダーだ」と伝える役割があります。<br><br>右側でheaderの構造を確認しましょう。", initialCode: "<header>\n    <h1>サイトのロゴ</h1>\n    <p>サイトのキャッチコピー</p>\n</header>" },
    { id: "4-4", title: "ナビゲーションメニュー：navタグ", content: "サイト内の他のページへのリンクが集まるメニューエリアには <b>nav（ナブ）タグ</b> を使います。一般的にはnavの中にulとliを使ってメニューを作ります。<br><br>右のコードで一般的なメニューの形を確認しましょう。", initialCode: "<nav>\n    <ul>\n        <li><a href=\"#\">ホーム</a></li>\n        <li><a href=\"#\">会社概要</a></li>\n        <li><a href=\"#\">ブログ</a></li>\n    </ul>\n</nav>" },
    { id: "4-5", title: "メインコンテンツ：mainタグ", content: "そのページの「主役」となる中身を囲むには <b>main（メイン）タグ</b> を使います。1つのページに1回だけしか使えません。<br><br>右のコードで、header、nav、mainの流れを確認しましょう。", initialCode: "<header><h1>ロゴ</h1></header>\n<nav>メニュー</nav>\n<main>\n    <h2>本日のニュース</h2>\n    <p>ここに主役の記事が入ります。</p>\n</main>" },
    { id: "4-6", title: "独立した記事：articleタグ", content: "ブログの記事やニュースの1件など、それ自体が単体で切り離されても意味が通じるひとかたまりには <b>article（アーティクル）タグ</b> を使います。<br><br>右側で、mainの中に記事が並ぶ様子を確認しましょう。", initialCode: "<main>\n    <article>\n        <h2>ブログ記事のタイトル1</h2>\n        <p>記事の本文がここに入ります。</p>\n    </article>\n    <article>\n        <h2>ブログ記事のタイトル2</h2>\n        <p>次の記事の本文です。</p>\n    </article>\n</main>" },
    { id: "4-7", title: "ページの足跡：footerタグ", content: "Webページの最下部にある、著作権（コピーライト）や会社情報を載せるエリアには <b>footer（フッター）タグ</b> を使います。<br><br>右側で、よくあるfooterの文字を確認しましょう。", initialCode: "<footer>\n    <p>&copy; 2026 自分の名前. All Rights Reserved.</p>\n</footer>" },
    { id: "4-8", title: "共通のグループ名：class属性", content: "CSSでデザインをつけるための「クラス名（グループ名）」をタグに与えるには <b>class属性</b> を使います。同じclass名はページ内に何回でも使えます。<br><br>右の複数のpタグに class=\"text-blue\" と書いてみましょう。", initialCode: "<p class=\"text-blue\">この文章は青くする予定です。</p>\n<p>これは普通の文章です。</p>\n<p>ここも青くしたいのでclassをつけてみましょう。</p>" },
    { id: "4-9", title: "背番号のような固有の名前：id属性", content: "classが学校の「班」のようなものなら、<b>id属性</b> は「出席番号」のように、ページ内で1つだけの特別な名前をつける時に使います。<br><br>右の一番大事な見出しに id=\"main-title\" をつけてみましょう。", initialCode: "<h1 id=\"main-title\">一番大事なタイトル</h1>\n<p>テキストなど</p>" },
    { id: "4-10", title: "第4章のまとめテスト！", content: "ここまで学んだレイアウトタグを使って、Webページの基本的な骨組みを組み立ててみましょう！<br><br>【課題】\n1. headerタグの中にh1でタイトルを書く\n2. mainタグの中にarticleタグを1つ作る\n3. footerタグの中に著作権（pタグなど）を書く", initialCode: "\n\n\n" }
];