const chapter6 = [
    { id: "6-1", title: "ホームページを作ろう！", content: "HTML編の総仕上げとして、これまでに学んだすべてのタグを総動員して、1つの「カフェのホームページの骨組み」を完成させましょう！<br><br>まずは全体の入れ物となる <b>div</b> を用意しました。右側を確認してください。", initialCode: "<div class=\"site-wrapper\">\n    \n    \n</div>" },
    { id: "6-2", title: "ヘッダーとロゴの配置", content: "まずはトップのヘッダーエリアです。<b>headerタグ</b> を使い、その中に一番大きな見出し <b>h1</b> でお店の名前を書きましょう。<br><br>右側のコメントの下に、headerとh1を書いてみましょう。", initialCode: "<div class=\"site-wrapper\">\n    \n    \n</div>" },
    { id: "6-3", title: "メニューバー（ナビゲーション）", content: "店名の下に、メニューバーを設置します。headerタグの中に、<b>navタグ</b>、<b>ulタグ</b>、<b>liタグ</b>、<b>aタグ</b> を組み合わせて、「ホーム」「メニュー」「アクセス」の3つのリンクを作ります。<br><br>右のコードを編集してみましょう。", initialCode: "<header>\n    <h1>Cafe HTML</h1>\n    \n    \n</header>" },
    { id: "6-4", title: "メイン看板画像の挿入", content: "お店の雰囲気を伝えるメイン画像を載せます。ここからは <b>mainタグ</b> の中に入ります。<b>imgタグ</b> を使って看板となる画像を表示させましょう。<br><br>右のコードのmainの中にimgタグを追加してください。", initialCode: "<header><h1>Cafe HTML</h1></header>\n<main>\n    \n    \n    \n</main>" },
    { id: "6-5", title: "お店の紹介セクション", content: "画像の次に、お店のこだわりを文章で紹介します。グループ化するための <b>sectionタグ</b> を使い、中に <b>h2タグ</b> で「当店のこだわり」、<b>pタグ</b> で説明を書きましょう。<br><br>右側のコードの続きに書いてみましょう。", initialCode: "<main>\n    <img src=\"https://picsum.photos/400/200\" alt=\"看板\">\n    \n    \n</main>" },
    { id: "6-6", title: "おすすめメニュー表の作成", content: "カフェのメニューを載せます。新しく <b>section</b> を作り、第2章で学んだ <b>tableタグ</b>（表）を使って、「コーヒー 400円」「サンドイッチ 600円」の表を作ってみましょう。<br><br>右側のコードに表を追加します。", initialCode: "<main>\n    \n    <section>\n        <h2>メニュー</h2>\n        \n        \n    </section>\n</main>" },
    { id: "6-7", title: "お問い合わせ・予約フォーム", content: "お客様が席の予約や問い合わせをできるように、第3章の <b>formタグ</b> を追加します。1行の入力欄（<b>input type=\"text\"</b>）と、送信ボタン（<b>input type=\"submit\"</b>）を設置しましょう。<br><br>右側にフォームを組み込みます。", initialCode: "<main>\n    \n    <section>\n        <h2>ご予約はこちら</h2>\n        \n        \n    </section>\n</main>" },
    { id: "6-8", title: "フッターの追加で完成！", content: "最後に、mainタグの外（下）に <b>footerタグ</b> を配置し、著作権の文字（&copy; 2026 Cafe HTML）を入れてページ全体を締めくくります。<br><br>右のコードの最下部にfooterを追加しましょう！", initialCode: "<header><h1>Cafe HTML</h1></header>\n<main>\n    <p>（これまでのコンテンツ）</p>\n</main>\n\n" },
    { id: "6-9", title: "全体のつながりを確認", content: "これまでバラバラに作ってきたパーツが合体した「完成形」のコードが右側にあります。各タグが正しい順番、正しい入れ子（親子関係）になっているか、スクロールしてじっくり確認してみましょう。", initialCode: "<header>\n    <h1>Cafe HTML</h1>\n    <nav><ul><li>ホーム</li><li>メニュー</li></ul></nav>\n</header>\n<main>\n    <img src=\"https://picsum.photos/400/200\" alt=\"店内\">\n    <section>\n        <h2>当店について</h2>\n        <p>落ち着いた空間を提供するカフェです。</p>\n    </section>\n</main>\n<footer>\n    <p>&copy; 2026 Cafe HTML</p>\n</footer>" },
    { id: "6-10", title: "HTML編・完全攻略テスト！", content: "おめでとうございます！これがHTML編の最終ステップです。<br>右側のエリアに、あなたがこれまでに学んだすべての知識を使って、「自由なオリジナルWebページ」を一つ作ってください！", initialCode: "\n\n" }
];