const chapter5 = [
    { id: "5-1", title: "クリックで開閉：detailsとsummary", content: "クリックすると詳細が開く「アコーディオンメニュー（よくある質問など）」を、HTMLだけで作ることができます。全体を <b>detailsタグ</b> で囲み、最初に見えているタイトルを <b>summaryタグ</b> で書きます。<br><br>右の実行結果の「詳細を見る」をクリックしてみてください。", initialCode: "<details>\n    <summary>詳細を見る（ここをクリック）</summary>\n    <p>隠れていた秘密のメッセージが表示されました！</p>\n</details>" },
    { id: "5-2", title: "動画を再生しよう：videoタグ", content: "ページ内で動画を再生するには <b>videoタグ</b> を使います。<b>controls属性</b> をつけると、再生・停止ボタンが自動で表示されます。<br><br>右側でサンプル動画が再生できるか確認してみましょう。", initialCode: "<video src=\"https://www.w3schools.com/html/mov_bbb.mp4\" controls width=\"320\">\n    お使いのブラウザは動画再生に対応していません。\n</video>" },
    { id: "5-3", title: "進捗メーター：progressタグ", content: "タスクの進み具合などをメーターで視覚的に表すには <b>progressタグ</b> を使います。<b>value属性</b>（現在の値）と <b>max属性</b>（最大値）を指定します。<br><br>右のコードのvalueの数字を書き換えて、メーターの動きを見てみましょう。", initialCode: "<p>学習の進捗度：</p>\n<progress value=\"70\" max=\"100\"></progress>" },
    { id: "5-4", title: "他からの引用：blockquoteタグ", content: "他のサイトや本から長めの文章を引用したことを示すには <b>blockquote（ブロッククォート）タグ</b> を使います。ブラウザでは、少し左側に隙間（インデント）が空いて表示されます。<br><br>右側で表示を確認しましょう。", initialCode: "<p>有名な格言です：</p>\n<blockquote>\n    「天才とは、1％のひらめきと99％の努力である。」\n</blockquote>" },
    { id: "5-5", title: "正しい日付：timeタグ", content: "人間が見る日付（〇年〇月〇日など）を、検索エンジンなどのロボットにも正しく伝えるために <b>timeタグ</b> を使います。<b>datetime属性</b> に「2026-05-18」のような形式で書きます。<br><br>右側のコードを確認しましょう。", initialCode: "<p>このサイトは <time datetime=\"2026-05-18\">2026年5月18日</time> に更新されました。</p>" },
    { id: "5-6", title: "プログラムのコード：codeタグ", content: "文章の中で、これがプログラムのコード（数式や英語の命令など）であることを示すには <b>codeタグ</b> を使います。等幅フォントというスッキリした文字に変わります。<br><br>右側のコードを見てみましょう。", initialCode: "<p>HTMLでは、改行するときに <code>&lt;br&gt;</code> タグを使います。</p>" },
    { id: "5-7", title: "図と注釈：figureとfigcaption", content: "イラストや写真などの図（img）と、その「説明文」をひとまとめのセットにするには、全体を <b>figureタグ</b> で囲み、説明文を <b>figcaptionタグ</b> で書きます。<br><br>右側で画像と説明文のセットを確認しましょう。", initialCode: "<figure>\n    <img src=\"https://picsum.photos/150/100\" alt=\"サンプル\">\n    <figcaption>図1：講義で用意したサンプル画像</figcaption>\n</figure>" },
    { id: "5-8", title: "カラーピッカー：input type=\"color\"", content: "第3章でやった入力欄（input）の応用です。<b>type=\"color\"</b> と書くと、ユーザーが色を直感的に選べるカラーピッカーが出現します。<br><br>右側の四角い色ボタンをクリックして、色を選んでみてください。", initialCode: "<form>\n    好きな色を選んでください：<br>\n    <input type=\"color\">\n</form>" },
    { id: "5-9", title: "スライダー：input type=\"range\"", content: "音量や数値の調整をスライダーで行わせたい場合は、<b>type=\"range\"</b> を使います。<b>min</b>（最小値）や <b>max</b>（最大値）も設定できます。<br><br>右側のツマミを動かしてみましょう。", initialCode: "<form>\n    音量調節：<br>\n    <input type=\"range\" min=\"0\" max=\"100\">\n</form>" },
    { id: "5-10", title: "第5章のまとめテスト！", content: "新しく学んだ便利なタグを組み合わせて、ちょっとリッチなコンテンツを作ってみましょう！<br><br>【課題】\n1. detailsとsummaryを使って「質問コーナー」を作る\n2. その中身（開いたときに出る文）に、progressタグを置く", initialCode: "\n\n\n" }
];